spring.application.name=AI-Powered-Expense-Tracker

#spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
#spring.datasource.username=root
#spring.datasource.password=#Raushan@55
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#server.port=8080

gemini.api.key=AIzaSyAIFLr7-KJ7z9Y9Sn_Llp5TY_4tKMH-ltc


spring.application.name=expense-tracker

spring.datasource.url=jdbc:mysql://shortline.proxy.rlwy.net:30282/railway

spring.datasource.username=root

spring.datasource.password=kLIyzCmuEpFlYleYmWYrznTaxgMWUyhM

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true